[package]
name = "watsch"
version = "0.1.0"
authors = ["Renee Gyllensvaan <rgyllensvaan@bison.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "4.0.14"
